
ver: 1.0

file:
    path: '/Users/xiaogangyang/data/ca_doga/Ni_pos1_mask2'
    # range: [0, 601, 1]
    range: [0, 73, 1]
    threshold: 100 # [readout values]
    frame: [0, 2048, 0, 2048] # [pixels]
    ext: 'h5'
    stacked: True
    h5:
        key: '/entry1/data/data'

comp:
    server: 'local'
    workers: 10
    functionid: 'd8461388-9442-4008-a5f1-2cfa112f6923'

geo:
    mask: 
        path: './codes/code-debruijn-2-8-000.npy'
        bitsizes: [15, 7.5] # [mu]
        thickness: 4.6 # [mu]
        resolution: 0.5
        smoothness: 0 # [mu]
        alpha: 0 
        widening: 1.7 # [mu]
        pad: 150
        stretch: 1.0

        focus:
            cenx: -0.97533203
            dist: 1.16650000
            cenz: -0.17089844
            anglex: -0.06152344
            angley: -0.68076172
            anglez: -1.28115234

        calibrate: 
            dist: [1.166, 1.186, 0.001] # [mm]

    scanner:
        angle: 0
        step: 1 # [mu]
        rot: [0.0045, -0.00684, -3.375e-5]
        axis: [1, 0, 0]

    detector: 
        shape: [2048, 2048] # [pixels]
        size: [409.6, 409.6] # [mm]
        rot: [-1.20139958, -1.21416739, -1.21878591] # [radian]
        pos: [28.871, 2.786, 513.140] # [mm]

    source: 
        offset: 0
        grid: [-0.816, -0.616, 0.001] # [mm]

algo:
    iter: 1
    pos: 
        method: 'lsqr' 
        regpar: 0
        init: 'spline'

    sig: 
        # method: 'splines' 
        method: 'dnn' 
        order: 1
        scale: 1
        init:
            maxsize: 120 
            avgsize: 20
            atol: 4
